version: '3'

services:
  amp-server:
    image: amp-server
    restart: always
    container_name: amp
    volumes:
      - /home/minecraft:/config
    ports:
      - 8080-8180:8080-8180
      - 25565:25565
      - 27015-27020:27015-27020
      - 2777-2778:2777-2778
